//! Generate `methods_generated.rs` from `abi/contract/yurt_abi_methods.toml`.
//!
//! Method IDs are pinned in TOML and emitted as `pub const METHOD_<NAME>: u32`
//! plus a `KNOWN_METHODS: &[(&str, u32)]` table the dispatch layer can
//! introspect. Reordering imports never renumbers; adding a method
//! requires explicit ID assignment in the TOML.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let workspace_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("workspace root")
        .to_path_buf();
    let methods_toml = workspace_root.join("abi/contract/yurt_abi_methods.toml");
    println!("cargo:rerun-if-changed={}", methods_toml.display());
    println!("cargo:rerun-if-changed=build.rs");

    let raw = fs::read_to_string(&methods_toml)
        .unwrap_or_else(|e| panic!("read {}: {e}", methods_toml.display()));
    let parsed: toml::Value = raw.parse().expect("parse yurt_abi_methods.toml");

    let methods = parsed
        .get("method")
        .and_then(|v| v.as_table())
        .expect("[method.*] section in yurt_abi_methods.toml");

    // BTreeMap to keep output order stable across cargo runs.
    let mut by_name: BTreeMap<String, (u32, String)> = BTreeMap::new();
    let mut by_id: BTreeMap<u32, String> = BTreeMap::new();
    for (name, body) in methods {
        let id = body
            .get("id")
            .and_then(|v| v.as_integer())
            .unwrap_or_else(|| panic!("method.{name} missing id"));
        let id = u32::try_from(id).unwrap_or_else(|_| panic!("method.{name} id out of u32 range"));
        let kind = body
            .get("kind")
            .and_then(|v| v.as_str())
            .unwrap_or("syscall")
            .to_owned();
        if let Some(prev) = by_id.insert(id, name.clone()) {
            panic!("duplicate method id {id} between {prev} and {name}");
        }
        by_name.insert(name.clone(), (id, kind));
    }

    let mut out = String::new();
    out.push_str("// Generated by build.rs from abi/contract/yurt_abi_methods.toml.\n");
    out.push_str("// Do not edit by hand — re-run cargo build to regenerate.\n\n");
    for (name, (id, _kind)) in &by_name {
        out.push_str(&format!(
            "pub const METHOD_{}: u32 = 0x{:x};\n",
            name.to_uppercase(),
            id
        ));
    }
    // KNOWN_METHODS is consumed by tests and by future host-interface-side
    // introspection helpers; allow dead_code for the wasm release build
    // where neither is compiled in.
    out.push_str("\n#[allow(dead_code)]\npub const KNOWN_METHODS: &[(&str, u32)] = &[\n");
    for (name, (id, _kind)) in &by_name {
        out.push_str(&format!("    (\"{name}\", 0x{id:x}),\n"));
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("methods_generated.rs");
    fs::write(&out_path, out).unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}
