// @generated by scripts/generate-native-abi.ts. Do not edit by hand.

/// Major version of the host/guest kernel ABI.
pub const YURT_ABI_VERSION_MAJOR: u32 = 1;

/// Minor version of the host/guest kernel ABI.
pub const YURT_ABI_VERSION_MINOR: u32 = 0;

/// Native record format version.
pub const YURT_ABI_RECORD_VERSION: u16 = 1;

/// Yurt product version surfaced through uname and procfs.
pub const YURT_VERSION_STR: &str = "0.1.0";

/// Yurt product major version.
pub const YURT_VERSION_MAJOR: u32 = 0;

/// Yurt product minor version.
pub const YURT_VERSION_MINOR: u32 = 1;

/// Yurt product patch version.
pub const YURT_VERSION_PATCH: u32 = 0;

/// Return immediately from host_wait when no child has exited.
pub const YURT_WAIT_NOHANG: u32 = 1;

/// Operation not permitted.
pub const EPERM: i32 = 1;

/// No such file or directory.
pub const ENOENT: i32 = 2;

/// No such process.
pub const ESRCH: i32 = 3;

/// Interrupted system call.
pub const EINTR: i32 = 4;

/// I/O error.
pub const EIO: i32 = 5;

/// Executable format error.
pub const ENOEXEC: i32 = 8;

/// Bad file descriptor.
pub const EBADF: i32 = 9;

/// No child processes.
pub const ECHILD: i32 = 10;

/// Resource temporarily unavailable.
pub const EAGAIN: i32 = 11;

/// Permission denied.
pub const EACCES: i32 = 13;

/// File exists.
pub const EEXIST: i32 = 17;

/// Not a directory.
pub const ENOTDIR: i32 = 20;

/// Invalid argument.
pub const EINVAL: i32 = 22;

/// Value too large for defined data type.
pub const EOVERFLOW: i32 = 75;

/// Connection reset by peer.
pub const ECONNRESET: i32 = 104;

/// Socket is not connected.
pub const ENOTCONN: i32 = 107;

/// Connection refused.
pub const ECONNREFUSED: i32 = 111;

/// No route to host.
pub const EHOSTUNREACH: i32 = 113;

/// Header at the front of every variable-size native request or response record.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct YurtAbiRecordHeader {
    /// Logical initialized record size in bytes.
    pub size: u32,
    /// Record version.
    pub version: u16,
    /// Record-specific flags.
    pub flags: u16,
}

/// Fixed output written by host_wait.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct YurtWaitResultV1 {
    /// Child pid that changed state.
    pub pid: i32,
    /// Exit code when exited normally, otherwise 0.
    pub exit_code: i32,
    /// Signal number when signaled, otherwise 0.
    pub signal: i32,
    /// Wait result flags.
    pub flags: i32,
}

/// Fixed output written by host_pipe.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct YurtPipeResultV1 {
    /// Read end file descriptor.
    pub read_fd: i32,
    /// Write end file descriptor.
    pub write_fd: i32,
}

/// Fixed output written by host_spawn.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct YurtSpawnResultV1 {
    /// Spawned process id.
    pub pid: i32,
}
