import { assertArrayIncludes } from "jsr:@std/assert@^1.0.19";
import { createKernelImports } from "../kernel-imports.ts";

const KERNEL_IMPORTS_BASELINE = [
  "host_pipe",
  "host_spawn",
  "host_mark_exec_child",
  "host_wait",
  "host_close_fd",
  "host_getpid",
  "host_getppid",
  "host_getuid",
  "host_geteuid",
  "host_getgid",
  "host_getegid",
  "host_setresuid",
  "host_setresgid",
  "host_umask",
  "host_getcwd",
  "host_realpath",
  "host_chdir",
  "host_fchdir",
  "host_getpriority",
  "host_setpriority",
  "host_sched_getscheduler",
  "host_sched_getparam",
  "host_sched_setscheduler",
  "host_sched_setparam",
  "host_sched_getaffinity",
  "host_sched_setaffinity",
  "host_getrlimit",
  "host_setrlimit",
  "host_kill",
  "host_read_fd",
  "host_write_fd",
  "host_dup",
  "host_dup_min",
  "host_dup2",
  "host_set_fd_descriptor_flags",
  "host_network_fetch",
  "host_socket_connect",
  "host_socket_listen",
  "host_socket_accept",
  "host_socket_send",
  "host_socket_recv",
  "host_socket_addr",
  "host_socket_set_no_delay",
  "host_socket_close",
  "host_extension_invoke",
  "host_setjmp",
  "host_longjmp",
  "host_fork",
  "host_yield",
  "host_list_processes",
  "host_stat",
  "host_read_file",
  "host_write_file",
  "host_readdir",
  "host_mkdir",
  "host_remove",
  "host_chmod",
  "host_chown",
  "host_fchown",
  "host_glob",
  "host_rename",
  "host_symlink",
  "host_readlink",
  "host_register_tool",
  "host_has_tool",
  "host_time",
  "host_read_command",
  "host_write_result",
  // Process groups / sessions
  "host_getpgid",
  "host_setpgid",
  "host_getsid",
  "host_setsid",
  "host_killpg",
  // TTY
  "host_isatty",
  "host_tcgetpgrp",
  "host_tcsetpgrp",
  "host_tcgetattr",
  "host_tcsetattr",
  "host_winsize",
  // TTY controlling terminal
  "host_tiocsctty",
  // DNS
  "host_dns_resolve",
  "host_get_local_addr",
];

Deno.test("kernel-imports baseline export names", () => {
  const imports = createKernelImports({
    memory: new WebAssembly.Memory({ initial: 1 }),
  });
  const names = Object.keys(imports);

  for (const expected of KERNEL_IMPORTS_BASELINE) {
    assertArrayIncludes(names, [expected]);
  }
});
